#%RAML 1.0 NamedExample
value:
  - id: "1"
    firstName: "Jhon"
    lastName: "willam"
    address: "2012 w highland"
    postal: "85013"
    country: "US"
    miles: 45
    creationDate: "2020-06-22T06:00:00+00:00"
    type: "personal"
  - id: "2"
    firstName: "mike"
    lastName: "brown"
    address: "2012 w Thomas"
    postal: "85013"
    country: "US"
    miles: 42
    creationDate: "2020-06-23T06:00:00+00:00"
    type: "business"
  