#%RAML 1.0 NamedExample
value:
  id: "43"
  firstName: "Jhon"
  lastName: "willam"
  address: "2012 w highland"
  postal: "85013"
  country: "US"
  miles: 45
  creationDate: "2020-06-22T06:00:00+00:00"
  type: "personal"